version: '2.4'

services:
  client:
    build:
      context: ./
      dockerfile: DockerfileRelease
    platform: linux/arm/v7
    image: vbstreetz/signatory-client:latest
    command: ./node_modules/.bin/serve ./build -s
    ports:
      - '${PORT}:5000'

  server:
    image: vbstreetz/signatory-client:latest
    command: ./node_modules/.bin/signatory -d ./data
    ports:
      - 1999:1999
