version: '2.4'

services:
  client:
    image: vbstreetz/signatory-client:latest
    command: yarn client
    ports:
      - '${PORT}:5000'

  server:
    image: vbstreetz/signatory-client:latest
    command: yarn server
    ports:
      - 1999:1999
