version: '2'

services:
  client:
    image: vbstreetz/signatory-client:latest
    command: ./node_modules/.bin/serve build
    ports:
      - '${PORT}:3000'

  server:
    image: vbstreetz/signatory-client:latest
    command: yarn server
    ports:
      - 1999:1999
