version: "2"

services:
  client:
    container_name: frontend
    build: ./frontend
    command: yarn start
    ports:
      - "${CLIENT_PORT}:3000"
    environment:
      NODE_PATH: ./src

  server:
    container_name: daemon
    build: ./daemon
    command: yarn start
    ports:
      - "${SERVER_PORT}:1999"
