version: '2'

services:
  client:
    build:
      context: ./
      dockerfile: DockerfileDev
    image: vbstreetz/signatory-client-dev:latest
    command: yarn start
    environment:
      NODE_PATH: ./src
      REACT_APP_IS_DEV: 1
      REACT_APP_INFURA_API_KEY: '${INFURA_API_KEY}'
    volumes:
      - ./:/tmp
      - /tmp/node_modules
    ports:
      - '${PORT}:4444'

  server:
    image: vbstreetz/signatory-client-dev:latest
    command: yarn server
    ports:
      - 1999:1999
