version: '2'

services:
  client:
    build:
      context: ./
      dockerfile: DockerfileRelease
    image: vbstreetz/signatory-client:latest
    command: ./node_modules/.bin/serve build
    ports:
      - '${PORT}:3000'
    environment:
      NODE_PATH: ./src
      REACT_APP_INFURA_API_KEY: '${INFURA_API_KEY}'

  server:
    build:
      context: ./
      dockerfile: DockerfileRelease
    image: vbstreetz/signatory-client:latest
    command: yarn server
    ports:
      - 1999:1999
