name: CI

on:
  push:
    branches: [buildx]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      # node
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - uses: actions/setup-node@v1
        with:
          node-version: '10.18.0'
      - run: yarn install
      - run: yarn build
      # docker
      - uses: actions/cache@v1
        with:
          path: ~/docker-cache
          key: ${{ runner.os }}-docker-buildx-${{ hashFiles('**/DockerfileRelease') }}
          restore-keys: ${{ runner.os }}-docker-buildx-
      - name: Set Up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Docker Login
        run: docker login -u vbstreetz -p ${{ secrets.dockerhub }}
      - name: Run Buildx
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm/v7,linux/arm64 \
            --tag vbstreetz/signatory-client:latest \
            --file ./DockerfileRelease \
            --cache-to=type=local,dest=~/docker-cache \
            --push \
            ./
